pyxis: importing docker image: doduo1.umcn.nl#tabea/spliceai:2.3
pyxis: imported docker image: doduo1.umcn.nl#tabea/spliceai:2.3
Traceback (most recent call last):
  File "/home/scripts/train_model.py", line 206, in <module>
    X = h5f['X' + str(idx)][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 366, in h5py._selector.Reader.read
OSError: [Errno 112] Can't read data (file read failed: time = Fri Jun 28 08:16:57 2024
, filename = '/data/retina_train_all.h5', file descriptor = 35, errno = 112, error message = 'Host is down', buf = 0x7f3fc9d2e010, total read size = 178140000, bytes this sub-read = 178140000, bytes actually read = 18446744073709551615, offset = 0)
